from model import Building, Data, Pickup

SC_VALLEY_BATTERY = Data(
    gridrange_x=10,
    gridrange_y=15,
    buildings=[
        Building("SHR1", 3, 3),
        Building("SHR2", 3, 3),
        Building("SHR3", 3, 3),
        Building("RU1", 3, 3),
        Building("RU2", 3, 3),
        Building("FU1", 3, 3),
        Building("FU2", 3, 3),
        Building("PACKU1", 6, 4),
    ],
    conveyor_joins=[
        (None, "SHR1"),
        (None, "SHR2"),
        (None, "SHR3"),
        (None, "RU1"),
        (None, "RU2"),
        ("RU1", "FU1"),
        ("RU2", "FU2"),
        ("SHR1", "PACKU1"),
        ("SHR2", "PACKU1"),
        ("SHR3", "PACKU1"),
        ("FU1", "PACKU1"),
        ("FU2", "PACKU1"),
    ],
    pickups=[
        Pickup(0, 1, orientation=2),
        Pickup(0, 4, orientation=2),
        Pickup(0, 7, orientation=2),
        Pickup(0, 10, orientation=2),
        Pickup(0, 13, orientation=2),
    ],
)

BUCK_CAPSULE_B = Data(
    gridrange_x=40,
    gridrange_y=11,
    buildings=[
        Building("RU1", 3, 3),
        Building("RU2", 3, 3),
        Building("RU3", 3, 3),
        Building("RU4", 3, 3),
        Building("MOULD1", 3, 3),
        Building("MOULD2", 3, 3),
        Building("SEED1", 5, 5),
        Building("PLANT1", 5, 5),
        Building("PLANT2", 5, 5),
        Building("SHR1", 3, 3),
        Building("FILL1", 6, 4),
    ],
    conveyor_joins=[
        (None, "RU1"),
        (None, "RU2"),
        (None, "RU3"),
        (None, "RU4"),
        ("RU1", "MOULD1"),
        ("RU2", "MOULD1"),
        ("RU3", "MOULD2"),
        ("RU4", "MOULD2"),
        ("SEED1", "PLANT1"),
        ("SEED1", "PLANT2"),
        ("PLANT1", "SEED1"),
        ("PLANT2", "SHR1"),
        ("SHR1", "FILL1"),
        ("SHR1", "FILL1"),
        ("MOULD1", "FILL1"),
        ("MOULD2", "FILL1"),
    ],
    pickups=[
        Pickup(0, 1, orientation=2),
        Pickup(0, 4, orientation=2),
        Pickup(0, 7, orientation=2),
        Pickup(0, 10, orientation=2),
    ],
    hints=lambda v: v._replace(
        building_x={b: 1 for b in ["RU1", "RU2", "RU3", "RU4"]},
        building_orientation={b: 2 for b in ["RU1", "RU2", "RU3", "RU4"]},
    ),
)

_hcvbat_leftmost = [
    "SHR1",
    "SHR2",
    "SHR3",
    "SHR4",
    "SHR5",
    "SHR6",
    "RU1",
    "RU2",
    "RU3",
    "RU4",
]
HC_VALLEY_BATTERY = Data(
    gridrange_x=40,
    gridrange_y=29,
    buildings=[
        Building("SHR1", 3, 3),
        Building("SHR2", 3, 3),
        Building("SHR3", 3, 3),
        Building("SHR4", 3, 3),
        Building("SHR5", 3, 3),
        Building("SHR6", 3, 3),
        Building("SEED1", 5, 5),
        Building("PLANT1", 5, 5),
        Building("PLANT2", 5, 5),
        Building("SEED2", 5, 5),
        Building("PLANT3", 5, 5),
        Building("PLANT4", 5, 5),
        Building("SHR7", 3, 3),
        Building("SHR8", 3, 3),
        Building("GRIND1", 6, 4),
        Building("GRIND2", 6, 4),
        Building("GRIND3", 6, 4),
        Building("RU1", 3, 3),
        Building("RU2", 3, 3),
        Building("RU3", 3, 3),
        Building("RU4", 3, 3),
        Building("SHR9", 3, 3),
        Building("SHR10", 3, 3),
        Building("SHR11", 3, 3),
        Building("SHR12", 3, 3),
        Building("GRIND4", 6, 4),
        Building("GRIND5", 6, 4),
        Building("RU5", 3, 3),
        Building("RU6", 3, 3),
        Building("FU1", 3, 3),
        Building("FU2", 3, 3),
        Building("PACKU1", 6, 4),
    ],
    conveyor_joins=[
        (None, "SHR1"),
        (None, "SHR2"),
        (None, "SHR3"),
        (None, "SHR4"),
        (None, "SHR5"),
        (None, "SHR6"),
        (None, "RU1"),
        (None, "RU2"),
        (None, "RU3"),
        (None, "RU4"),
        ("SHR1", "GRIND1"),
        ("SHR2", "GRIND1"),
        ("SHR3", "GRIND2"),
        ("SHR4", "GRIND2"),
        ("SHR5", "GRIND3"),
        ("SHR6", "GRIND3"),
        ("SEED1", "PLANT1"),
        ("SEED1", "PLANT2"),
        ("PLANT1", "SEED1"),
        ("PLANT2", "SHR7"),
        ("SEED2", "PLANT3"),
        ("SEED2", "PLANT4"),
        ("PLANT3", "SEED2"),
        ("PLANT4", "SHR8"),
        ("SHR7", "GRIND1"),
        ("SHR7", "GRIND2"),
        ("SHR7", "GRIND3"),
        ("RU1", "SHR9"),
        ("RU2", "SHR10"),
        ("RU3", "SHR11"),
        ("RU4", "SHR12"),
        ("SHR8", "GRIND4"),
        ("SHR8", "GRIND5"),
        ("SHR9", "GRIND4"),
        ("SHR10", "GRIND4"),
        ("SHR11", "GRIND5"),
        ("SHR12", "GRIND5"),
        ("GRIND4", "RU5"),
        ("GRIND5", "RU6"),
        ("RU5", "FU1"),
        ("RU6", "FU2"),
        ("GRIND1", "PACKU1"),
        ("GRIND2", "PACKU1"),
        ("GRIND3", "PACKU1"),
        ("FU1", "PACKU1"),
        ("FU2", "PACKU1"),
    ],
    pickups=[
        Pickup(0, 1, orientation=2),
        Pickup(0, 4, orientation=2),
        Pickup(0, 7, orientation=2),
        Pickup(0, 10, orientation=2),
        Pickup(0, 13, orientation=2),
        Pickup(0, 16, orientation=2),
        Pickup(0, 19, orientation=2),
        Pickup(0, 22, orientation=2),
        Pickup(0, 25, orientation=2),
        Pickup(0, 28, orientation=2),
    ],
    hints=lambda v: v._replace(
        building_x={b: 2 for b in _hcvbat_leftmost},
        building_orientation={b: 2 for b in _hcvbat_leftmost},
    ),
)

HC_VALLEY_BATTERY_REDUCED = Data(
    gridrange_x=30,
    gridrange_y=29,
    buildings=[
        Building("SEED1", 5, 5),
        Building("PLANT1", 5, 5),
        Building("PLANT2", 5, 5),
        Building("SEED2", 5, 5),
        Building("PLANT3", 5, 5),
        Building("PLANT4", 5, 5),
        Building("SHR7", 3, 3),
        Building("SHR8", 3, 3),
        Building("GRIND1", 6, 4),
        Building("GRIND2", 6, 4),
        Building("GRIND3", 6, 4),
        Building("SHR9", 3, 3),
        Building("SHR10", 3, 3),
        Building("SHR11", 3, 3),
        Building("SHR12", 3, 3),
        Building("GRIND4", 6, 4),
        Building("GRIND5", 6, 4),
        Building("RU5", 3, 3),
        Building("RU6", 3, 3),
        Building("FU1", 3, 3),
        Building("FU2", 3, 3),
        Building("PACKU1", 6, 4),
    ],
    conveyor_joins=[
        (None, "GRIND1"),
        (None, "GRIND1"),
        (None, "GRIND2"),
        (None, "GRIND2"),
        (None, "GRIND3"),
        (None, "GRIND3"),
        (None, "SHR9"),
        (None, "SHR10"),
        (None, "SHR11"),
        (None, "SHR12"),
        ("SEED1", "PLANT1"),
        ("SEED1", "PLANT2"),
        ("PLANT1", "SEED1"),
        ("PLANT2", "SHR7"),
        ("SEED2", "PLANT3"),
        ("SEED2", "PLANT4"),
        ("PLANT3", "SEED2"),
        ("PLANT4", "SHR8"),
        ("SHR7", "GRIND1"),
        ("SHR7", "GRIND2"),
        ("SHR7", "GRIND3"),
        ("SHR8", "GRIND4"),
        ("SHR8", "GRIND5"),
        ("SHR9", "GRIND4"),
        ("SHR10", "GRIND4"),
        ("SHR11", "GRIND5"),
        ("SHR12", "GRIND5"),
        ("GRIND4", "RU5"),
        ("GRIND5", "RU6"),
        ("RU5", "FU1"),
        ("RU6", "FU2"),
        ("GRIND1", "PACKU1"),
        ("GRIND2", "PACKU1"),
        ("GRIND3", "PACKU1"),
        ("FU1", "PACKU1"),
        ("FU2", "PACKU1"),
    ],
    pickups=[
        Pickup(0, 1, orientation=2),
        Pickup(0, 4, orientation=2),
        Pickup(0, 7, orientation=2),
        Pickup(0, 10, orientation=2),
        Pickup(0, 13, orientation=2),
        Pickup(0, 16, orientation=2),
        Pickup(0, 19, orientation=2),
        Pickup(0, 22, orientation=2),
        Pickup(0, 25, orientation=2),
        Pickup(0, 28, orientation=2),
    ],
    hints=None,
)
